services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: longanai-frontend:latest
    container_name: longanai-frontend
    ports:
      - "3008:3008"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - longanai-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: longanai-backend:latest
    container_name: longanai-backend
    ports:
      - "8005:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    depends_on:
      - db
      - redis
    networks:
      - longanai-network
    volumes:
      - ./static:/app/static
      - ./google-credentials.json:/app/google-credentials.json

  db:
    image: postgres:15-alpine
    container_name: longanai-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - longanai-network

  redis:
    image: redis:7-alpine
    container_name: longanai-redis
    ports:
      - "6380:6379"
    networks:
      - longanai-network

volumes:
  postgres_data:

networks:
  longanai-network:
    driver: bridge 