services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: longanai-frontend:latest
    container_name: longanai-frontend
    ports:
      - "3008:3008"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8005
    depends_on:
      - backend
    networks:
      - longanai-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: longanai-backend:latest
    container_name: longanai-backend
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/longanai
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
      - redis
    networks:
      - longanai-network

  db:
    image: postgres:15-alpine
    container_name: longanai-db
    environment:
      - POSTGRES_DB=longanai
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - longanai-network

  redis:
    image: redis:7-alpine
    container_name: longanai-redis
    ports:
      - "6380:6379"
    networks:
      - longanai-network

  nginx:
    image: nginx:alpine
    container_name: longanai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - longanai-network

volumes:
  postgres_data:

networks:
  longanai-network:
    driver: bridge 